In [3]:
import pandas as pd
from pathlib import Path

# Locate the existing dataset
BASE_DIR = Path.cwd()
DATA_FILE = BASE_DIR / "data" / "Software Questions.csv"

# Check that the dataset exists
if not DATA_FILE.exists():
    raise FileNotFoundError(
        f"Dataset not found at: {DATA_FILE}\n"
        "Check your folder location and CSV filename."
    )

# Load the original dataset
df = pd.read_csv(DATA_FILE, encoding="cp1252")

print("Original dataset loaded successfully!")
print("Number of rows:", len(df))
print("\nDifficulty distribution:")
print(df["Difficulty"].value_counts())

df.head()

Original dataset loaded successfully!
Number of rows: 200

Difficulty distribution:
Difficulty
Medium    111
Hard       82
Easy        7
Name: count, dtype: int64

,Question Number,Question,Answer,Category,Difficulty
0,1,What is the difference between compilation and...,Compilation translates source code into machin...,General Programming,Medium
1,2,Explain the concept of polymorphism.,Polymorphism allows objects of different class...,General Programming,Medium
2,3,Define encapsulation and give an example.,Encapsulation bundles data and methods in a cl...,General Programming,Hard
3,4,"What is an abstract class, and how is it diffe...",An abstract class can't be instantiated and ca...,General Programming,Medium
4,5,Describe the principles of Object-Oriented Pro...,"OOP principles include encapsulation, inherita...",General Programming,Medium

In [4]:
easy_questions = [
    {
        "Question": "What is software engineering?",
        "Answer": "Software engineering is the systematic process of designing, developing, testing, and maintaining software.",
        "Category": "Software Engineering",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a variable in programming?",
        "Answer": "A variable is a named storage location used to hold a value that a program can access or change.",
        "Category": "Programming Fundamentals",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a function in programming?",
        "Answer": "A function is a reusable block of code that performs a particular task and may accept inputs and return a result.",
        "Category": "Programming Fundamentals",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is the difference between a compiler and an interpreter?",
        "Answer": "A compiler translates a program into another form, often machine code, before execution. An interpreter executes program instructions through an interpreter at runtime.",
        "Category": "Programming Fundamentals",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is debugging?",
        "Answer": "Debugging is the process of finding, analyzing, and fixing errors in a program.",
        "Category": "Software Testing",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is an algorithm?",
        "Answer": "An algorithm is a finite sequence of clear steps used to solve a problem or complete a task.",
        "Category": "Data Structures and Algorithms",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a data type?",
        "Answer": "A data type defines the kind of value a variable can store, such as an integer, string, Boolean, or floating-point number.",
        "Category": "Programming Fundamentals",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is an array?",
        "Answer": "An array is a data structure that stores a collection of elements, usually accessed using an index.",
        "Category": "Data Structures and Algorithms",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a database?",
        "Answer": "A database is an organized collection of data that can be stored, retrieved, and managed.",
        "Category": "Databases",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is SQL used for?",
        "Answer": "SQL is a language used to define, query, insert, update, and manage data in relational databases.",
        "Category": "Databases",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a primary key in a database?",
        "Answer": "A primary key is a column or combination of columns that uniquely identifies each row in a database table.",
        "Category": "Databases",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a foreign key?",
        "Answer": "A foreign key is a column or set of columns that references a key in another table, helping establish relationships between tables.",
        "Category": "Databases",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is object-oriented programming?",
        "Answer": "Object-oriented programming is a programming approach that organizes software around objects containing data and behavior.",
        "Category": "Object-Oriented Programming",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a class in object-oriented programming?",
        "Answer": "A class is a blueprint that defines the properties and behaviors that its objects can have.",
        "Category": "Object-Oriented Programming",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is an object in programming?",
        "Answer": "An object is an instance of a class that can hold data and provide behavior defined by that class.",
        "Category": "Object-Oriented Programming",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is inheritance in object-oriented programming?",
        "Answer": "Inheritance allows a class to reuse or extend properties and methods from another class.",
        "Category": "Object-Oriented Programming",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is encapsulation?",
        "Answer": "Encapsulation combines data and related methods in a unit, such as a class, and controls how its internal state is accessed.",
        "Category": "Object-Oriented Programming",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is an API?",
        "Answer": "An API is an interface that allows software components or applications to communicate using defined rules.",
        "Category": "Web Development",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is the difference between HTTP and HTTPS?",
        "Answer": "HTTPS uses encryption through TLS to protect data exchanged between a client and a server, while HTTP does not provide that transport encryption.",
        "Category": "Networking and Web",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is version control?",
        "Answer": "Version control tracks changes to files over time and helps developers collaborate and restore earlier versions.",
        "Category": "Software Development Tools",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is Git?",
        "Answer": "Git is a distributed version control system used to track changes in files and coordinate software development.",
        "Category": "Software Development Tools",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is unit testing?",
        "Answer": "Unit testing checks a small, isolated part of a program, such as a function or method, to verify that it behaves as expected.",
        "Category": "Software Testing",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is a software bug?",
        "Answer": "A software bug is a defect that causes a program to behave incorrectly or fail to meet its requirements.",
        "Category": "Software Testing",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is the purpose of comments in source code?",
        "Answer": "Comments explain code or provide context for developers and are generally ignored by the program during execution.",
        "Category": "Programming Fundamentals",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is the difference between frontend and backend development?",
        "Answer": "Frontend development focuses on the parts of an application users interact with, while backend development handles server-side logic, data processing, and services.",
        "Category": "Web Development",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is responsive web design?",
        "Answer": "Responsive web design makes a website adapt its layout to different screen sizes and devices.",
        "Category": "Web Development",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is an operating system?",
        "Answer": "An operating system manages computer hardware and provides services that applications use to run.",
        "Category": "Operating Systems",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is the purpose of a software requirements document?",
        "Answer": "It describes what a software system should do, its constraints, and the needs it must satisfy.",
        "Category": "Software Engineering",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is the software development life cycle?",
        "Answer": "The software development life cycle is a structured process covering activities such as planning, requirements analysis, design, implementation, testing, deployment, and maintenance.",
        "Category": "Software Engineering",
        "Difficulty": "Easy"
    },
    {
        "Question": "What is the difference between syntax errors and logical errors?",
        "Answer": "A syntax error violates the programming language's rules, while a logical error allows a program to run but produces an incorrect result.",
        "Category": "Programming Fundamentals",
        "Difficulty": "Easy"
    }
]

new_df = pd.DataFrame(easy_questions)

print("New Easy questions prepared:", len(new_df))
new_df.head()

New Easy questions prepared: 30

,Question,Answer,Category,Difficulty
0,What is software engineering?,Software engineering is the systematic process...,Software Engineering,Easy
1,What is a variable in programming?,A variable is a named storage location used to...,Programming Fundamentals,Easy
2,What is a function in programming?,A function is a reusable block of code that pe...,Programming Fundamentals,Easy
3,What is the difference between a compiler and ...,A compiler translates a program into another f...,Programming Fundamentals,Easy
4,What is debugging?,"Debugging is the process of finding, analyzing...",Software Testing,Easy

In [5]:
# Confirm that the expected column exists
required_columns = ["Question", "Answer", "Category", "Difficulty"]

for column in required_columns:
    if column not in df.columns:
        raise ValueError(f"Missing required column: {column}")

# Normalize question text for comparison
def normalize_question(question):
    return " ".join(str(question).casefold().split())

existing_questions = set(
    df["Question"].dropna().map(normalize_question)
)

# Remove duplicate questions within the new list
new_df = new_df.drop_duplicates(
    subset=["Question"],
    keep="first"
).copy()

# Exclude questions already in the original dataset
new_df["_normalized_question"] = new_df["Question"].map(
    normalize_question
)

new_df = new_df[
    ~new_df["_normalized_question"].isin(existing_questions)
].copy()

new_df = new_df.drop(columns=["_normalized_question"])

print("New questions after duplicate checking:", len(new_df))
print("\nQuestions to be added:")
display(new_df[["Question", "Category", "Difficulty"]])

New questions after duplicate checking: 30

Questions to be added:

,Question,Category,Difficulty
0,What is software engineering?,Software Engineering,Easy
1,What is a variable in programming?,Programming Fundamentals,Easy
2,What is a function in programming?,Programming Fundamentals,Easy
3,What is the difference between a compiler and ...,Programming Fundamentals,Easy
4,What is debugging?,Software Testing,Easy
5,What is an algorithm?,Data Structures and Algorithms,Easy
6,What is a data type?,Programming Fundamentals,Easy
7,What is an array?,Data Structures and Algorithms,Easy
8,What is a database?,Databases,Easy
9,What is SQL used for?,Databases,Easy
10,What is a primary key in a database?,Databases,Easy
11,What is a foreign key?,Databases,Easy
12,What is object-oriented programming?,Object-Oriented Programming,Easy
13,What is a class in object-oriented programming?,Object-Oriented Programming,Easy
14,What is an object in programming?,Object-Oriented Programming,Easy
15,What is inheritance in object-oriented program...,Object-Oriented Programming,Easy
16,What is encapsulation?,Object-Oriented Programming,Easy
17,What is an API?,Web Development,Easy
18,What is the difference between HTTP and HTTPS?,Networking and Web,Easy
19,What is version control?,Software Development Tools,Easy
20,What is Git?,Software Development Tools,Easy
21,What is unit testing?,Software Testing,Easy
22,What is a software bug?,Software Testing,Easy
23,What is the purpose of comments in source code?,Programming Fundamentals,Easy
24,What is the difference between frontend and ba...,Web Development,Easy
25,What is responsive web design?,Web Development,Easy
26,What is an operating system?,Operating Systems,Easy
27,What is the purpose of a software requirements...,Software Engineering,Easy
28,What is the software development life cycle?,Software Engineering,Easy
29,What is the difference between syntax errors a...,Programming Fundamentals,Easy

In [6]:
# Match the original column structure
# The original dataset may have an additional Question Number column.
if "Question Number" in df.columns:
    new_df.insert(
        0,
        "Question Number",
        range(
            int(pd.to_numeric(df["Question Number"], errors="coerce").max()) + 1,
            int(pd.to_numeric(df["Question Number"], errors="coerce").max()) + 1
            + len(new_df)
        )
    )

# Keep only the columns present in the original dataset
new_df = new_df[df.columns.intersection(new_df.columns).tolist()]

# Combine original and new questions
expanded_df = pd.concat(
    [df, new_df],
    ignore_index=True
)

print("Original rows:", len(df))
print("New questions added:", len(new_df))
print("Expanded dataset rows:", len(expanded_df))

print("\nUpdated difficulty distribution:")
print(expanded_df["Difficulty"].value_counts())

display(expanded_df.tail(10))

Original rows: 200
New questions added: 30
Expanded dataset rows: 230

Updated difficulty distribution:
Difficulty
Medium    111
Hard       82
Easy       37
Name: count, dtype: int64

,Question Number,Question,Answer,Category,Difficulty
220,221,What is Git?,Git is a distributed version control system us...,Software Development Tools,Easy
221,222,What is unit testing?,"Unit testing checks a small, isolated part of ...",Software Testing,Easy
222,223,What is a software bug?,A software bug is a defect that causes a progr...,Software Testing,Easy
223,224,What is the purpose of comments in source code?,Comments explain code or provide context for d...,Programming Fundamentals,Easy
224,225,What is the difference between frontend and ba...,Frontend development focuses on the parts of a...,Web Development,Easy
225,226,What is responsive web design?,Responsive web design makes a website adapt it...,Web Development,Easy
226,227,What is an operating system?,An operating system manages computer hardware ...,Operating Systems,Easy
227,228,What is the purpose of a software requirements...,"It describes what a software system should do,...",Software Engineering,Easy
228,229,What is the software development life cycle?,The software development life cycle is a struc...,Software Engineering,Easy
229,230,What is the difference between syntax errors a...,A syntax error violates the programming langua...,Programming Fundamentals,Easy

In [7]:
OUTPUT_FILE = BASE_DIR / "data" / "expanded_software_questions.csv"

# Create the data folder if it does not exist
OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

expanded_df.to_csv(OUTPUT_FILE, index=False)

print("Expanded dataset saved successfully!")
print("File location:", OUTPUT_FILE.resolve())

Expanded dataset saved successfully!
File location: C:\Users\mj000\OneDrive\Desktop\AI-semproj\SemProject_MLEngine\data\expanded_software_questions.csv

In [8]:
difficulty_counts = expanded_df["Difficulty"].value_counts()

print("Difficulty counts:")
print(difficulty_counts)

print("\nDifficulty percentages:")
print((expanded_df["Difficulty"].value_counts(normalize=True) * 100).round(2))

if "Easy" in difficulty_counts.index:
    print("\nEasy questions added to the dataset.")
    print("Total Easy questions:", difficulty_counts["Easy"])
else:
    print("\nCheck that the Difficulty values use the label 'Easy'.")

Difficulty counts:
Difficulty
Medium    111
Hard       82
Easy       37
Name: count, dtype: int64

Difficulty percentages:
Difficulty
Medium    48.26
Hard      35.65
Easy      16.09
Name: proportion, dtype: float64

Easy questions added to the dataset.
Total Easy questions: 37

In [9]:
# Standardize difficulty labels for counting
expanded_df["Difficulty"] = expanded_df["Difficulty"].astype(str).str.strip()

# Find categories shared by the dataset
difficulty_counts = expanded_df["Difficulty"].value_counts()

if not {"Easy", "Medium", "Hard"}.issubset(set(difficulty_counts.index)):
    raise ValueError(
        "The dataset must contain Easy, Medium, and Hard difficulty labels."
    )

# Use the size of the smallest class
samples_per_class = int(difficulty_counts[["Easy", "Medium", "Hard"]].min())

balanced_df = pd.concat(
    [
        expanded_df[expanded_df["Difficulty"] == level].sample(
            n=samples_per_class,
            random_state=42
        )
        for level in ["Easy", "Medium", "Hard"]
    ],
    ignore_index=True
)

# Shuffle the rows
balanced_df = balanced_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

BALANCED_FILE = BASE_DIR / "data" / "balanced_experimental_dataset.csv"

balanced_df.to_csv(BALANCED_FILE, index=False)

print("Balanced dataset saved to:", BALANCED_FILE.resolve())
print("\nBalanced difficulty distribution:")
print(balanced_df["Difficulty"].value_counts())

print("\nTotal rows:", len(balanced_df))

Balanced dataset saved to: C:\Users\mj000\OneDrive\Desktop\AI-semproj\SemProject_MLEngine\data\balanced_experimental_dataset.csv

Balanced difficulty distribution:
Difficulty
Hard      37
Easy      37
Medium    37
Name: count, dtype: int64

Total rows: 111

In [10]:
# VALIDATION: Load the balanced dataset to confirm it was saved correctly

import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd()
DATA_FILE = BASE_DIR / "data" / "balanced_experimental_dataset.csv"

if not DATA_FILE.exists():
    raise FileNotFoundError(
        f"Balanced dataset not found: {DATA_FILE.resolve()}"
    )

df = pd.read_csv(DATA_FILE, encoding="cp1252")

print("Dataset loaded successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset loaded successfully
Rows: 111
Columns: 5

Column names:
['Question Number', 'Question', 'Answer', 'Category', 'Difficulty']

,Question Number,Question,Answer,Category,Difficulty
0,87,Explain the principles of least privilege and ...,Least privilege limits access rights; defense ...,Security,Hard
1,202,What is a variable in programming?,A variable is a named storage location used to...,Programming Fundamentals,Easy
2,229,What is the software development life cycle?,The software development life cycle is a struc...,Software Engineering,Easy
3,168,Design a system for efficient storage and retr...,"Optimize for write-heavy loads, use time-based...",Database Systems,Hard
4,105,What is the difference between SQL and NoSQL d...,"SQL databases are structured, use SQL, and are...",Back-end,Medium

In [11]:
# Check that the essential columns exist
required_columns = ["Question", "Answer", "Category", "Difficulty"]

missing_columns = [
    column for column in required_columns
    if column not in df.columns
]

if missing_columns:
    raise ValueError(f"Missing columns: {missing_columns}")

# Check missing values
print("Missing values per column:")
print(df[required_columns].isnull().sum())

# Check blank questions and answers
for column in ["Question", "Answer", "Category", "Difficulty"]:
    df[column] = df[column].astype("string").str.strip()

blank_questions = df["Question"].isna() | df["Question"].eq("")
blank_answers = df["Answer"].isna() | df["Answer"].eq("")

print("\nBlank questions:", int(blank_questions.sum()))
print("Blank answers:", int(blank_answers.sum()))

# Normalize question text for duplicate detection
def normalize_question(question):
    return " ".join(str(question).casefold().split())

normalized = df["Question"].dropna().map(normalize_question)
duplicate_count = int(normalized.duplicated().sum())

print("\nDuplicate question texts:", duplicate_count)

# Difficulty distribution
print("\nDifficulty counts:")
print(df["Difficulty"].value_counts())

print("\nDifficulty percentages:")
print(
    (df["Difficulty"].value_counts(normalize=True) * 100)
    .round(2)
    .astype(str) + "%"
)

Missing values per column:
Question      0
Answer        0
Category      0
Difficulty    0
dtype: int64

Blank questions: 0
Blank answers: 0

Duplicate question texts: 2

Difficulty counts:
Difficulty
Hard      37
Easy      37
Medium    37
Name: count, dtype: Int64

Difficulty percentages:
Difficulty
Hard      33.33%
Easy      33.33%
Medium    33.33%
Name: proportion, dtype: str

In [12]:
# Show rows with missing or blank questions/answers and duplicate questions

print("Rows with missing or blank questions/answers:")
display(df[blank_questions | blank_answers])

print("\nDuplicate question rows:")
duplicate_mask = df["Question"].notna() & df["Question"].map(
    normalize_question
).duplicated(keep=False)

display(
    df.loc[duplicate_mask, required_columns]
    .sort_values("Question")
)

# Check class balance
counts = df["Difficulty"].value_counts()

print("\nIs the dataset balanced?")
print(
    "Yes"
    if len(counts) == 3 and counts.nunique() == 1
    else "No — check the counts above."
)

Rows with missing or blank questions/answers:

Empty DataFrame
Columns: [Question Number, Question, Answer, Category, Difficulty]
Index: []

Duplicate question rows:

,Question,Answer,Category,Difficulty
10,What are microservices and how do they differ ...,Microservices are a software development techn...,Back-end,Hard
71,What are microservices and how do they differ ...,Microservices are a software development techn...,Back-end,Medium
7,What is continuous integration in DevOps?,Continuous integration is the practice of auto...,DevOps,Medium
89,What is continuous integration in DevOps?,Continuous integration is the practice of auto...,DevOps,Medium

Is the dataset balanced?
Yes